octopgpy/octopgpy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('octopgpyapp.urls')),
    path('admin/', admin.site.urls),
]

octopgpy/octopgpyapp/urls.py
from django.urls import path

from . import views
app_name = 'octopgpyapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('app/<int:id>/', views.showapp, name='showapp'),
    path('app/new/', views.newapp, name='newapp'),   
    path('app/<int:id>/documents/', views.documents, name='documents'),
    path('app/<int:id>/newdocument/', views.newdocument, name='newdocument'),

    path('app/<int:id>/document/<int:did>/fields', views.fields, name='fields'),
    path('app/<int:id>/document/<int:did>/field/<int:fid>', views.fields, name='fields'),


    path('app/<int:id>/appdocument/<int:did>', views.appdocument, name='appdocument'),
    path('app/<int:id>/appdocument/<int:did>/newentry', views.newentry, name='newentry'),
]

octopgpy/octopgpyapp/models.py
from ast import Delete
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
class App(models.Model):
    name = models.CharField(max_length=30)
   
class Document(models.Model):
    name = models.CharField(max_length=30)
    app = models.ForeignKey(App,on_delete=models.CASCADE)
    child_document =  models.ForeignKey(
        'Document', on_delete=models.DO_NOTHING, null=True, blank=True, related_name='sub_child')

TYPE_CHOICES = (
    ('text','text'),
    ('integer','integer'),
    ('numeric', 'numeric'),
    ('timestamp','timestamp'), 
)

class Field(models.Model):
    class Meta:
        unique_together = (('name', 'document'),)
    name = models.CharField(max_length=30,null=True,blank=True)
    descriptive_name = models.CharField(max_length=30,null=True,blank=True)
    type = models.CharField(max_length=30,default='text',choices=TYPE_CHOICES,null=True,blank=True)
    document = models.ForeignKey(Document,on_delete=models.DO_NOTHING)
    is_calculated = models.BooleanField(default=False)
    calculation_func = models.CharField(max_length=30,null=True,blank=True)
    calculation_func_args = models.CharField(max_length=30,null=True,blank=True)
    # models.JSONField(null=True)            


class Func(models.Model):
    name = models.CharField(max_length=30)
    body = models.CharField(max_length=1024)

class Param(models.Model):
    name = models.CharField(max_length=30) 
    paramtype =  models.CharField(max_length=30) 
    func = models.ForeignKey(Func, on_delete=models.DO_NOTHING)

class DocumentView(models.Model):
    name = models.CharField(max_length=30) 
    parent_document =  models.ForeignKey(
        'Document', on_delete=models.CASCADE, related_name='document_sub_child')
    parent_documentview =   models.ForeignKey('DocumentView', on_delete=models.CASCADE)
    document = models.ForeignKey(Document,on_delete=models.DO_NOTHING)

AGGREGATES = (
    ('sum','sum'),
    ('avg','avg')
)
class FromClause(models.Model):
    name = models.CharField(max_length=30) 
    dw = models.ForeignKey(DocumentView, on_delete=models.CASCADE)
    agg = models.CharField(max_length=30,choices=AGGREGATES) 

# class WhereClause(models.Model):

# class GroupByClause(models.Model):

# class HavingClause(models.Model):

# class SelectClause(models.Model):

# class OrderByClause(models.Model):

# class LimitClause(models.Model):

octopgpy/octopgpyapp/forms.py
from django import forms
from . models import App,Document,Field

class AppForm(forms.ModelForm):
    class Meta:
        model = App
        fields = ('name',)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('name',)


class FieldForm(forms.ModelForm):
    field_file = forms.FileField(required=False)
    class Meta:
        model = Field
        fields = ('name', 'descriptive_name','type','is_calculated','calculation_func','calculation_func_args','field_file',)

octopgpy/octopgpyapp/views.py
import csv
from email import header 
import io

from msilib import datasizemask
from django.shortcuts import render,HttpResponseRedirect,reverse,get_object_or_404

from django.http import HttpResponse

from . forms import AppForm,DocumentForm,FieldForm
from . models import App,Document,Field
from django.db import connection



def index(request):
    apps = App.objects.all()
    return render(request,'octopgpyapp/index.html',context= {'apps':apps})

def showapp(request,id):
    app = App.objects.get(pk=id)
    documents = Document.objects.filter(app_id=id)
    return render(request, 'octopgpyapp/app.html', {'app': app,'documents':documents})

def newapp(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AppForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print(form['name'])
            form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # return HttpResponseRedirect('/')
            return HttpResponseRedirect(reverse('octopgpyapp:index'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = AppForm()

    return render(request, 'octopgpyapp/newapp.html', {'form': form})
def documents(request,id):
    app = App.objects.get(pk=id)
    documents = Document.objects.filter(app_id=id)

    return render(request, 'octopgpyapp/documents.html', {'app': app,'documents':documents})
def newdocument(request,id):
    # if this is a POST request we need to process the form data
    app = App.objects.get(pk=id)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DocumentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_document = form.save(commit=False)
            new_document.app = app
            new_document.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('octopgpyapp:documents', args=(app.id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = DocumentForm()

    return render(request, 'octopgpyapp/newdocument.html', {'form': form,'app':app})

def fields(request,id,did,fid=0):

    action = request.GET.get('action')
    print(action)
    document = Document.objects.get(pk=did)
    fields = Field.objects.filter(document_id=did)
    form = None
  
    app = App.objects.get(pk=id)
    if fid:
        field = get_object_or_404(Field, id=fid)
    else:
        field = None

    print(request.method,fid,field)

    if request.method == 'POST':
        if request.FILES.get('field_file'):
            field_file = request.FILES.get('field_file')
            file = field_file.read().decode('utf-8')
            reader = csv.DictReader(io.StringIO(file))
            # Generate a list comprehension
            headers = next(reader)
            
            for header_field in headers:
                cleaned_field_file = header_field.lower().replace(' ','_').replace('.','')
                field = Field.objects.update_or_create(descriptive_name=header_field,name=cleaned_field_file,type='text',document=document)

            return HttpResponseRedirect(request.path)
      
        # check whether it's valid:
        form = FieldForm(instance=field,data=request.POST)
        if form.is_valid():
            new_field = form.save(commit=False)
            # if not fid:
            new_field.document = document
            new_field.save()
            return HttpResponseRedirect(request.path)
            # return HttpResponseRedirect(reverse('octopgpyapp:fields', args=(app.id,did,)))
    # if a GET (or any other method) we'll create a blank form
    elif action == 'edit':
        field = Field.objects.get(pk=fid)
        form = FieldForm(instance=field)
    elif action == 'delete':
        Field.objects.get(pk=fid).delete()
        return HttpResponseRedirect(reverse('octopgpyapp:fields', args=(app.id,did,)))
    elif action == 'generate':
        generate_document_db(did)
        return HttpResponseRedirect(reverse('octopgpyapp:fields', args=(app.id,did,)))
    elif action == 'delete_all':
        Field.objects.all().delete()
    else:
        form = FieldForm()

    return render(request, 'octopgpyapp/fields.html', context={'app':app,'document':document, 'fields':fields,'form':form,'fid':fid})


def appdocument(request,id,did):
    # if this is a POST request we need to process the form data
    app = App.objects.get(pk=id)
    document = Document.objects.get(pk=did)

    
    
    document_data = f"select * from {app.name}_{document.name} limit 10" 
    cols,res = fetch_sql_cmd(document_data)
    print(document_data,res)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DocumentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_document = form.save(commit=False)
            new_document.app = app
            new_document.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('octopgpyapp:appdocument', args=(app.id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = DocumentForm()

    return render(request, 'octopgpyapp/appdocument.html', {'form': form,'app':app,'document':document,'cols':cols,'res':res})

def newentry(request,id,did):
    # if this is a POST request we need to process the form data
    app = App.objects.get(pk=id)
    document = Document.objects.get(pk=did)
    fields = Field.objects.filter(document_id=did)
    # generate_document_db(did)
    if request.method == 'POST':    
        print(request.FILES)
        if request.FILES.get('newentry_file'):
            field_file = request.FILES.get('newentry_file')
            file = field_file.read().decode('utf-8')
            reader = csv.DictReader(io.StringIO(file))
            # Generate a list comprehension
            headers = next(reader)           
            
            for line in reader:
                print(line)
                f_names = []
                f_vals = []
               
                for f in fields:
                    print(f.name)
                    # if not f.is_calculated or f.name != 'file_name':                        
                    
                    
                    if f.descriptive_name != 'File Name' and not f.is_calculated :
                        f_names.append(f.name)
                        val = line[f.descriptive_name].replace("'","''")                       
                        if f.type != "numeric" and f.type != 'int':
                            f_vals.append(f"'{val}'")                    
                        else:
                            f_vals.append(val)
                f_names.append("file_name")
                f_vals.append(f"'{field_file.name}'")
                sql = f"insert into {app.name}_{document.name}({','.join(f_names)}) values({','.join(f_vals)})"
                execute_sql_cmd(sql)

            return HttpResponseRedirect(request.path)
        # create a form instance and populate it with data from the request:
        data = request.POST
       
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print(data,fields)
        f_names = []
        f_vals = []
        for f in fields:
            if not f.is_calculated:
                f_names.append(f.name)
                if f.type != "numeric":
                    f_vals.append(f"'{data[f.name]}'")
                else:
                    f_vals.append(data[f.name])
                
        sql = f"insert into {app.name}_{document.name}({','.join(f_names)}) values({','.join(f_vals)})"
        print(sql,f_names,f_vals)
        execute_sql_cmd(sql)
        return HttpResponseRedirect(request.path)
    # if a GET (or any other method) we'll create a blank form
    else:
        form = DocumentForm()

    return render(request, 'octopgpyapp/newentry.html', {'form': form,'app':app,'document':document,'fields':fields})

def generate_document_db(did):
    document = Document.objects.get(pk=did)
    app = document.app
    fields = Field.objects.filter(document_id=did)
    print("====================")
    print(document,app,fields)   

    # create empty table
    table_name = f"{app.name}_{document.name}"
    sql = f"create table if not exists {table_name}();"    
    print(sql)
    execute_sql_cmd(sql)
    
    f = []
    for field in fields:
        # field.type = 'text' if not field.type else field.type
        if field.is_calculated:
            f.append(f"alter table {table_name}  add if not exists {field.name} {field.type} GENERATED ALWAYS AS ({field.calculation_func}({field.calculation_func_args})) stored")
        else:
            f.append(f"alter table {table_name}  add if not exists {field.name} {field.type}")
    print(f)
    alter_table_cmds = ';'.join(f)
    print(alter_table_cmds)
    execute_sql_cmd(alter_table_cmds)

def execute_sql_cmd(sql):
    print(sql)
    with connection.cursor() as cursor:
        cursor.execute(sql)
   

def fetch_sql_cmd(sql):
    print(sql)
    with connection.cursor() as cursor:
        cursor.execute(sql)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
    return cols,rows

octopgpy/octopgpyapp/templates/octopgpyapp/app.html
{% extends "octopgpyapp/base.html" %}

{% block content %}

<div class="hero">
<h1>{{app.name}}<a href="{% url 'octopgpyapp:documents' id=1 %}" class="btn btn-outline-success">Documents</a></h1>

<div class="row">
    <div class="col col-3">
        <h3>Menu</h3>
        {% for doc in documents %}
            <a class="btn" href="{% url 'octopgpyapp:appdocument' id=app.id did=doc.id%}">{{doc.name}}</a>
        {% endfor %}
    </div>
</div>

</div>
{% endblock %}

octopgpy/octopgpyapp/templates/octopgpyapp/appdocument.html
{% extends "octopgpyapp/base.html" %}

{% block content %}

<div class="hero">
<h1>{{app.name}}<a href="{% url 'octopgpyapp:documents' id=1 %}" class="btn btn-outline-success">Documents</a></h1>

<h4>Document <em>{{document.name}}</em></h4>
<h3>Menu</h3>
<a href="{% url 'octopgpyapp:newentry' id=1 did=document.id %}">New  Entry</a>
<div class="row">
    <div class="col col-6">
        <table class="table table-striped table-sm">
            <thead>
               
                <tr>
                    {% for col in cols %}
                    <th>{{col}}</th>
                    {% endfor %}
                    <th>+</th>
                </tr>
              
            </thead>
            {% for row in res%}
            <tr>
                {% for r in row%}
             
                <td> {{r|safe}} </td>
               
                {% endfor %}

            </tr>   
            {% endfor %}
            </table>
    </div>
</div>

</div>
{% endblock %}

octopgpy/octopgpyapp/templates/octopgpyapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

octopgpy/octopgpyapp/templates/octopgpyapp/documents.html
{% extends "octopgpyapp/base.html" %}

{% block content %}

<div class="hero">
    <h1>{{app.name}}<a class="btn btn-outline-success" href="{% url 'octopgpyapp:newdocument' id=app.id %}">New Document</a></h1>
    {% for doc in documents %}
    <h1>{{doc.name}}<a class="btn btn-outline-success" href="{% url 'octopgpyapp:fields' id=app.id did=doc.id %}">fields</a></h1>
    {% endfor %}
</div>
{% endblock %}

octopgpy/octopgpyapp/templates/octopgpyapp/fields.html
{% extends "octopgpyapp/base.html" %}

{% block content %}
<h1><a href="{% url 'octopgpyapp:documents' id=app.id %}"><-</a>{{document.name}}</h1>
<div class="row">

    <div class="col col-6">
        <table>
           
            {% for field in fields %}
            <tr>
                <td>{{field.name}}</td>
                <td><a href="{% url 'octopgpyapp:fields' id=app.id did=document.id fid=field.id %}?action=edit">Edit</a></td>
                <td><a onclick="return confirm()" href="{% url 'octopgpyapp:fields' id=app.id did=document.id fid=field.id %}?action=delete">Delete</a></td>
             
            </tr>
        
           
            {% endfor %}
        </table>
       
    </div>
    <div class="col col-6">
            <form action="{% url 'octopgpyapp:fields' id=app.id did=document.id fid=fid %}" method="post"     enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Submit">
            </form>
           <a href="{% url 'octopgpyapp:fields' id=app.id did=document.id fid=0 %}?action=generate">Generate</a>
           <a onclick="return confirm('delete all')" href="{% url 'octopgpyapp:fields' id=app.id did=document.id fid=0 %}?action=delete_all">Delete All</a>
   
    </div>
</div>

<div class="hero">
   
  


</div>
{% endblock %}

octopgpy/octopgpyapp/templates/octopgpyapp/index.html
{% extends "octopgpyapp/base.html" %}

{% block content %}

<div class="hero">
  <h1>Apps<a href="{% url 'octopgpyapp:newapp' %}" class="btn btn-outline-success">New</a></h1>
  <div class="row">
    {% for app in apps %}
    <div class="col col-3">
      <div class="card" style="width: 18rem;margin:1em">
        <div class="card-body">
          <h5 class="card-title">{{app.name}}</h5>
          <!-- <h6 class="card-subtitle mb-2 text-muted">Library Management App</h6>
            <p class="card-text">Manage books, see due date</p> -->
          <!-- <a href="#" class="card-link">Card link</a> -->
          <a href="{% url 'octopgpyapp:showapp' id=app.id %}" class="card-link">Go There</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>




</div>
{% endblock %}

octopgpy/octopgpyapp/templates/octopgpyapp/newapp.html
{% extends "octopgpyapp/base.html" %}

{% block content %}

<div class="hero">
  <form action="{% url 'octopgpyapp:newapp' %}" method="post">
    {% csrf_token %}
   {{form}}
    <input type="submit" value="Submit">
</form>
</div>
{% endblock %}

octopgpy/octopgpyapp/templates/octopgpyapp/newdocument.html
{% extends "octopgpyapp/base.html" %}

{% block content %}

<div class="hero">
  <form action="{% url 'octopgpyapp:newdocument' id=app.id %}" method="post">
    {% csrf_token %}
   {{form}}
    <input type="submit" value="Submit">
</form>
</div>
{% endblock %}

octopgpy/octopgpyapp/templates/octopgpyapp/newentry.html
{% extends "octopgpyapp/base.html" %}

{% block content %}
<h1>New Entry</h1>
<div class="hero">
    <h1>{{app.name}}<a href="{% url 'octopgpyapp:documents' id=1 %}" class="btn btn-outline-success">Documents</a></h1>

    <h4>Document <em>{{document.name}}</em></h4>
    <h3>Menu</h3>
    <a href="{% url 'octopgpyapp:newentry' id=1 did=document.id %}">New Entry</a>

    {{app.name}}_{{document.name}}

    <form action="{% url 'octopgpyapp:newentry' id=1 did=document.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for f in fields %}
        {% if not f.is_calculated %}
            <label style="width:6em">{{f.name}}</label>
            {% if f.type == 'numeric' %}
                <input type="number" name="{{f.name}}" />
                <br/>
            {% elif f.type == 'date' %}
                <input type="date" name="{{f.name}}" />
                <br/>
            {% else%}
                <input type="text" name="{{f.name}}" />
                <br/>
            {% endif %}
        {% endif %}
        {% endfor %}

        <p>
            <label for="id_newentry_file">New Entry file:</label>
            <input type="file" name="newentry_file" id="id_newentry_file">
            
            
              
            
          </p>

        <input type="submit" />
    </form>
</div>
{% endblock %}